name: meu_dim
description: Projeto para auxiliar no controle financeiro.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  cloud_firestore: ^4.8.0
  device_preview: ^1.1.0
  firebase_auth: ^4.6.2
  firebase_core: ^2.13.1
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  uuid: ^3.0.7
  flutter_masked_text: ^0.8.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/images/logo.png
    - lib/images/author.png
    - lib/images/google.png    
